sp:
  user-service:
    users: [{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"}]

spring:
  application:
    name: user-service
    
server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh
